# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

epanechnikov_l2norm_runningC <- function(x, r) {
    .Call(`_CompStat_epanechnikov_l2norm_runningC`, x, r)
}

eval_kdensC <- function(kcode, grid, x, bw) {
    .Call(`_CompStat_eval_kdensC`, kcode, grid, x, bw)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib CompStat
NULL

vmC <- function(y, n) {
    .Call(`_CompStat_vmC`, y, n)
}

vmC2 <- function(y, n) {
    .Call(`_CompStat_vmC2`, y, n)
}

