# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_y_by_zC <- function(w, y) {
    .Call(`_CompStat_f_y_by_zC`, w, y)
}

cond_pC <- function(w, y) {
    .Call(`_CompStat_cond_pC`, w, y)
}

dQC <- function(v, w, y) {
    .Call(`_CompStat_dQC`, v, w, y)
}

dQC2 <- function(v, w, y) {
    .Call(`_CompStat_dQC2`, v, w, y)
}

lll_gradC <- function(design, coef, y, pen_matrix, lambda) {
    .Call(`_CompStat_lll_gradC`, design, coef, y, pen_matrix, lambda)
}

lllC <- function(design, coef, y, pen_matrix, lambda) {
    .Call(`_CompStat_lllC`, design, coef, y, pen_matrix, lambda)
}

SGD_CPP_PRIMITIVE <- function(design, coef, y, pen_matrix, lambda, lr, batch_size, maxiter, objtarget, beta_1, beta_2, eps, amsgrad, seed) {
    .Call(`_CompStat_SGD_CPP_PRIMITIVE`, design, coef, y, pen_matrix, lambda, lr, batch_size, maxiter, objtarget, beta_1, beta_2, eps, amsgrad, seed)
}

epanechnikov_l2norm_runningC <- function(x, r) {
    .Call(`_CompStat_epanechnikov_l2norm_runningC`, x, r)
}

eval_kdensC <- function(kcode, grid, x, bw) {
    .Call(`_CompStat_eval_kdensC`, kcode, grid, x, bw)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib CompStat
NULL

vmC <- function(y, n) {
    .Call(`_CompStat_vmC`, y, n)
}

vmC2 <- function(y, n) {
    .Call(`_CompStat_vmC2`, y, n)
}

