# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getOne <- function() {
    .Call(`_CompStat_getOne`)
}

eval_kdensC <- function(kcode, grid, x, bw) {
    .Call(`_CompStat_eval_kdensC`, kcode, grid, x, bw)
}

